---
- hosts: server
  gather_facts: false
  become: true
  vars_files:
   - vars/default.yml

  tasks:

# =============== Prepare necessary packages =============== # 

   - name: Install aptitude using apt
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: Install Necessary Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]

# =============== Install Docker-compose =============== #

   - name: apt-key Docker
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Add Docker Repository
     apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: Run "apt-get update"
     apt:
      update_cache: yes

   - name: Install Docker Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose' ]

   - name: add docker to user group
     command: sudo usermod -aG docker {{ remote_user }}
     
   - name: enable Docker
     systemd:
      name: docker
      state: started
      enabled: yes