---
- hosts: server
  gather_facts: false
  become: true
  vars:
    gitlab_install: false
  tasks:

# =============== Prepare necessary packages =============== # 

   - name: Install aptitude using apt
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: Install Necessary Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]

# =============== Install Docker-compose =============== #

   - name: apt-key Docker
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Add Docker Repository
     apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: Run "apt-get update"
     apt:
      update_cache: yes

   - name: Install Docker Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose', 'gnupg2', 'pass' ]

   - name: add docker to user group
     shell: "usermod -aG docker {{ ansible_user }}"
     
   - name: enable Docker
     systemd:
      name: docker
      state: started
      enabled: yes
      
# =============== Install Gitlab-runner =============== #

   - name: Download gitlab_runner
     get_url: 
       url="https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
       dest="/etc/gitlab-runner_amd64.deb"
     when: gitlab_install
     
   - name: Install gitlab_runner
     apt:
      deb: "/etc/gitlab-runner_amd64.deb"
     when: gitlab_install
     
   - name: enable gitlab_runner
     systemd:
      name: gitlab-runner
      state: started
      enabled: yes
     when: gitlab_install
     
   - name: add docker to gitlab-runner and restart docker
     shell: "usermod -aG docker gitlab-runner && service docker restart"
     when: gitlab_install
