---
- hosts: server
  gather_facts: false
  become: true
  vars_files:
   - vars/default.yml

  tasks:

# =============== Prepare necessary packages =============== # 

   - name: Install Necessary Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]

# =============== Install Docker-compose =============== #

   - name: apt-key Docker
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: 
     command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu \ $(lsb_release -cs) stable"

   - name: Run "apt-get update"
     apt:
      update_cache: yes

   - name: Install Docker Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose' ]

   - name: add docker to user group
     user:
      name: docker
      shell: /bin/bash
      groups: "{{ ansible_user }}"
      append: yes
     
   - name: enable Docker
     systemd:
      name: docker
      state: started
      enabled: yes